org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false

# Mod Information
mod_id=mctrace
mod_name=MCTrace
mod_license=MIT
mod_version=1.0.0
mod_group_id=net.mctrace
mod_authors=MCTrace Team
mod_description=Next-generation Vulkan Hardware Ray Tracing, AMD FSR, and Modern Shading Engine for Minecraft.

# Target Versions
minecraft_version=26.2
neoforge_version=26.2.0.86
neoform_version=26.2
